import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'राष्ट्रीय आपातकालीन प्रतिक्रिया (पुलिस / अग्निशमन / एम्बुलेंस)',
    number: '112',
    description: 'तत्काल आपातकालीन सहायता के लिए 24/7 एकीकृत अखिल भारतीय आपातकालीन सेवा।',
    available: '24/7 टोल-फ्री आपातकालीन सेवा',
    isClickableEmergency: true,
  },
  {
    label: 'महिला हेल्पलाइन (मिशन शक्ति)',
    number: '181',
    description: 'संकटग्रस्त महिलाओं के लिए राष्ट्रीय 24/7 टोल-फ्री सहायता और रेफरल हेल्पलाइन।',
    available: '24/7 राष्ट्रीय सहायता संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय महिला आयोग (NCW) हेल्पलाइन',
    number: '14490',
    description: 'हिंसा या संकट का सामना कर रही महिलाओं के लिए राष्ट्रीय महिला आयोग की आधिकारिक हेल्पलाइन।',
    available: 'राष्ट्रीय सहायता एवं रेफरल',
    isClickableEmergency: false,
  },
  {
    label: 'नालसा (NALSA) विधिक सहायता हेल्पलाइन',
    number: '15100',
    description: 'वैधानिक अधिकारों और विधिक सहायता क्लीनिकों के लिए टोल-फ्री राष्ट्रीय हेल्पलाइन।',
    available: 'मुफ्त कानूनी सहायता एवं मार्गदर्शन',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय साइबर अपराध हेल्पलाइन (वित्तीय धोखाधड़ी)',
    number: '1930',
    description: 'ऑनलाइन वित्तीय धोखाधड़ी की त्वरित शिकायत दर्ज कराने के लिए आधिकारिक राष्ट्रीय हेल्पलाइन।',
    available: 'वित्तीय साइबर धोखाधड़ी सहायता',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'आपातकालीन प्रतिक्रिया सहायता प्रणाली (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'नागरिकों को स्थानीय पुलिस, चिकित्सा और अग्निशमन प्रतिक्रिया दलों से सीधे जोड़ने वाला राष्ट्रव्यापी आपातकालीन मंच।',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    officialSourceUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    sourceTitle: 'Emergency Response Support System (ERSS)',
    publisher: 'गृह मंत्रालय, भारत सरकार',
    accessedAt: '2026-03-01',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '112 भारत का राष्ट्रव्यापी एकीकृत आपातकालीन नंबर है।',
    limitations: 'केवल राष्ट्रीय आपातकालीन नंबर; परिचालन प्रेषण संबंधित राज्य/केंद्र शासित प्रदेश आपातकालीन प्रतिक्रिया केंद्रों द्वारा नियंत्रित होता है।',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'आधिकारिक 24/7 राष्ट्रव्यापी आपातकालीन नंबर। जीवन के लिए खतरे की स्थिति में तुरंत 112 डायल करें।',
    isEmergency112: true,
  },
  {
    id: 'res-whl-181',
    name: 'महिला हेल्पलाइन (181 - मिशन शक्ति)',
    category: 'National Helpline',
    description:
      'मिशन शक्ति के तहत संकटग्रस्त महिलाओं को आपातकालीन और गैर-आपातकालीन रेफरल, परामर्श और वन स्टॉप सेंटर से समन्वय प्रदान करने वाली राष्ट्रीय 24/7 टोल-फ्री हेल्पलाइन।',
    contactType: 'phone',
    contactValue: '181',
    officialUrl: 'https://missionshakti.wcd.gov.in/',
    officialSourceUrl: 'https://missionshakti.wcd.gov.in/',
    sourceTitle: 'Mission Shakti - Women Helpline 181 Guidelines',
    publisher: 'महिला एवं बाल विकास मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'महिला एवं बाल विकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd-whl',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'मिशन शक्ति महिला हेल्पलाइन 181 को सूचीबद्ध करता है और एकीकृत सहायता प्रदान करने के रूप में वन स्टॉप सेंटर योजना का वर्णन करता है।',
    limitations: 'राष्ट्रीय कार्यक्रम की जानकारी सत्यापित है; स्थानीय टेलीकॉम रूटिंग और राज्य स्तरीय उपलब्धता की अलग से पुष्टि आवश्यक है।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'मिशन शक्ति के तहत राष्ट्रीय सहायता हेल्पलाइन। जान के खतरे की स्थिति में हमेशा सीधे 112 डायल करें।',
    isEmergency112: false,
  },
  {
    id: 'res-ncw-helpline',
    name: 'राष्ट्रीय महिला आयोग (NCW) महिला हेल्पलाइन',
    category: 'National Helpline',
    description:
      'संकटग्रस्त महिलाओं के लिए राष्ट्रीय महिला आयोग की आधिकारिक हेल्पलाइन, जो त्वरित सहायता, शिकायत निवारण और संस्थागत मार्गदर्शन की सुविधा प्रदान करती है।',
    contactType: 'phone',
    contactValue: '14490',
    officialUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    officialSourceUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    sourceTitle: 'NCW Cells - NCW Women Helpline (14490)',
    publisher: 'राष्ट्रीय महिला आयोग, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'राष्ट्रीय महिला आयोग (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'एनसीडब्ल्यू महिला हेल्पलाइन 14490 संकटग्रस्त महिलाओं और सहायता/रेफरल जानकारी के लिए एक आधिकारिक एनसीडब्ल्यू हेल्पलाइन है।',
    limitations: 'केवल राष्ट्रीय एनसीडब्ल्यू हेल्पलाइन विवरण और 14490। तत्काल हस्तक्षेप या कानूनी परिणाम की गारंटी नहीं देता।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'राष्ट्रीय सहायता और रेफरल हेल्पलाइन। मार्गदर्शन और शिकायत दर्ज कराने के लिए सीधे 14490 डायल करें।',
    isEmergency112: false,
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA) विधिक सहायता हेल्पलाइन',
    category: 'Legal Aid',
    description:
      'विधिक सेवा प्राधिकरण अधिनियम की धारा 12(c) के तहत महिलाओं सहित पात्र व्यक्तियों को मुफ्त कानूनी परामर्श, वकील सहायता और वैधानिक मार्गदर्शन प्रदान करने वाली संस्था।',
    contactType: 'phone',
    contactValue: '15100',
    officialUrl: 'https://nalsa.gov.in/',
    officialSourceUrl: 'https://nalsa.gov.in/',
    sourceTitle: 'National Legal Services Authority Legal Aid Portal & FAQs',
    publisher: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA)',
    accessedAt: '2026-10-08',
    sourceOwner: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'नालसा (NALSA) 15100 को अपनी टोल-फ्री विधिक सहायता हेल्पलाइन के रूप में पहचानता है।',
    limitations: 'राष्ट्रीय नालसा कानूनी सहायता हेल्पलाइन और सामान्य कानूनी सहायता विवरण। स्थानीय वकील नियुक्ति के लिए जिला डीएलएसए से समन्वय आवश्यक है।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'राष्ट्रीय कानूनी सहायता मार्गदर्शन हेल्पलाइन। यह किसी विशिष्ट कानूनी परिणाम या तुरंत प्रतिनिधित्व का वादा नहीं करती।',
    isEmergency112: false,
  },
  {
    id: 'res-cyber-portal',
    name: 'राष्ट्रीय साइबर अपराध हेल्पलाइन (1930 - वित्तीय धोखाधड़ी)',
    category: 'Cyber Crime',
    description:
      'गृह मंत्रालय के तहत नागरिकों द्वारा ऑनलाइन वित्तीय साइबर धोखाधड़ी और अनधिकृत लेनदेन की रिपोर्ट करने के लिए समर्पित आधिकारिक राष्ट्रीय हेल्पलाइन।',
    contactType: 'phone',
    contactValue: '1930',
    officialUrl: 'https://cybercrime.gov.in',
    officialSourceUrl: 'https://cybercrime.gov.in',
    sourceTitle: 'Citizen Financial Cyber Fraud Reporting System (1930)',
    publisher: 'गृह मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '1930 नागरिकों की वित्तीय साइबर धोखाधड़ी रिपोर्टिंग के लिए समर्पित राष्ट्रीय साइबर अपराध हेल्पलाइन है।',
    limitations: 'विशेष रूप से ऑनलाइन वित्तीय धोखाधड़ी की घटनाओं के लिए समर्पित हेल्पलाइन। यह सामान्य आपातकालीन नंबर नहीं है; न ही हर गैर-वित्तीय साइबर अपराध के लिए जांच मार्ग है।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'वित्तीय साइबर धोखाधड़ी की रिपोर्ट करने के लिए आधिकारिक हेल्पलाइन। तत्काल शारीरिक खतरे या सामान्य आपातकाल के लिए 112 पर कॉल करें।',
    isEmergency112: false,
  },
  {
    id: 'res-one-stop-centres',
    name: 'सखी वन स्टॉप सेंटर (Sakhi OSC Scheme)',
    category: 'Counseling & Support',
    description:
      'हिंसा से प्रभावित महिलाओं को चिकित्सा सहायता, पुलिस सुविधा, कानूनी सहायता और अस्थायी आश्रय प्रदान करने वाले एकीकृत सहायता केंद्र।',
    contactType: 'in-person',
    contactValue: 'जिला अस्पताल / नामित ओएससी परिसर (स्थानीय स्तर पर पुष्टि करें)',
    officialUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    officialSourceUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    sourceTitle: 'One Stop Centre Scheme Guidelines & Mission Shakti',
    publisher: 'महिला एवं बाल विकास मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'महिला एवं बाल विकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd-osc',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'मिशन शक्ति वन स्टॉप सेंटर योजना को एकीकृत सहायता और साहाय्य प्रदान करने के रूप में वर्णित करता है।',
    limitations: 'राष्ट्रीय कार्यक्रम की जानकारी सत्यापित है। स्थानीय पते, फोन नंबर और खुलने के समय की अलग से पुष्टि आवश्यक है।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'व्यक्तिगत उपस्थिति संदर्भ। जाने से पहले कृपया स्थानीय जिला केंद्र के सटीक पते और कार्य समय की पुष्टि करें।',
    isEmergency112: false,
  },
  {
    id: 'res-local-counseling',
    name: 'जिला परामर्श एवं परिवार मार्गदर्शन प्रकोष्ठ',
    category: 'Counseling & Support',
    description:
      'स्थानीय पारिवारिक परामर्श और विवाद निवारण के लिए जिला प्रशासन संदर्भ।',
    contactType: 'phone',
    contactValue: 'जिला प्रकोष्ठ संदर्भ (प्रशासनिक सत्यापन लंबित)',
    officialUrl: '',
    officialSourceUrl: '',
    sourceTitle: 'District Administrative Directory Reference',
    publisher: 'राज्य / जिला प्रशासन',
    accessedAt: '2026-02-15',
    sourceOwner: 'जिला प्रशासन',
    sourceId: 'src-district-ref',
    lastVerifiedDate: '2026-02-15',
    nextReviewDueDate: '2026-08-15',
    verificationStatus: 'needs-verification',
    verificationScope: 'pending',
    verifiedClaim: '',
    limitations: 'स्थानीय संपर्क विवरण प्रशासनिक सत्यापन के अधीन हैं। अलग से पुष्टि के बिना निर्भर न रहें।',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'संदर्भ जानकारी का सत्यापन लंबित है। सार्वजनिक उपयोग से पहले आधिकारिक स्रोत से पुष्टि करें।',
    isEmergency112: false,
  },
];
