import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'राष्ट्रीय आपातकालीन प्रतिक्रिया (पुलिस / अग्निशमन / एम्बुलेंस)',
    number: '112',
    description: 'तत्काल आपातकालीन सहायता के लिए 24/7 एकीकृत अखिल भारतीय आपातकालीन सेवा।',
    available: '24/7 टोल-फ्री',
    isClickableEmergency: true,
  },
  {
    label: 'महिला हेल्पलाइन (राष्ट्रीय)',
    number: '1091 (सार्वजनिक उपयोग से पहले आधिकारिक स्रोत से पुष्टि करें)',
    description: 'संकटग्रस्त महिलाओं के लिए हेल्पलाइन संदर्भ। प्रशासनिक पुष्टि के अधीन।',
    available: 'टोल-फ्री संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय साइबर अपराध हेल्पलाइन',
    number: '1930 (सार्वजनिक उपयोग से पहले आधिकारिक स्रोत से पुष्टि करें)',
    description: 'साइबर वित्तीय धोखाधड़ी और डिजिटल अपराधों के लिए सरकारी रिपोर्टिंग हेल्पलाइन।',
    available: 'राष्ट्रीय संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय महिला आयोग (NCW)',
    number: '7827170170 (सार्वजनिक उपयोग से पहले आधिकारिक स्रोत से पुष्टि करें)',
    description: 'परामर्श और प्रक्रियात्मक मार्गदर्शन के लिए राष्ट्रीय महिला आयोग हेल्पलाइन।',
    available: 'हेल्पडेस्क संदर्भ',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'आपातकालीन प्रतिक्रिया सहायता प्रणाली (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'नागरिकों को स्थानीय पुलिस, चिकित्सा और अग्निशमन प्रतिक्रिया दलों से सीधे जोड़ने वाला राष्ट्रव्यापी आपातकालीन मंच।',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://112.gov.in',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    verificationStatus: 'verified',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'आधिकारिक 24/7 राष्ट्रव्यापी आपातकालीन नंबर। सीधी आपातकालीन कॉलिंग के लिए क्लिक करने योग्य।',
    isEmergency112: true,
  },
  {
    id: 'res-one-stop-centres',
    name: 'सखी वन स्टॉप सेंटर (Sakhi OSC)',
    category: 'Counseling & Support',
    description:
      'हिंसा से प्रभावित महिलाओं को चिकित्सा सहायता, पुलिस सुविधा, कानूनी सहायता और अस्थायी आश्रय प्रदान करने वाले एकीकृत सहायता केंद्र।',
    contactType: 'in-person',
    contactValue: 'जिला अस्पताल / नामित ओएससी परिसर',
    officialUrl: 'https://wcd.nic.in',
    sourceOwner: 'महिला एवं बाल विकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'जाने से पहले आधिकारिक जिला प्रशासन से स्थानीय केंद्र का सटीक पता और संपर्क सत्यापित करें।',
  },
  {
    id: 'res-ncw-helpline',
    name: 'राष्ट्रीय महिला आयोग (NCW) 24/7 हेल्पलाइन',
    category: 'National Helpline',
    description:
      'हिंसा या अधिकारों के उल्लंघन का सामना कर रही महिलाओं के लिए शिकायत निवारण और परामर्श सुविधा प्रदान करने वाली हेल्पलाइन।',
    contactType: 'phone',
    contactValue: '7827170170 (प्लेसहोल्डर - उपयोग से पहले पुष्टि करें)',
    officialUrl: 'http://ncw.nic.in',
    sourceOwner: 'राष्ट्रीय महिला आयोग (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'गैर-क्लिक करने योग्य संदर्भ। उपयोग से पहले आधिकारिक एनसीडब्ल्यू पोर्टल से पुष्टि करें।',
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA) / डीएलएसए क्लीनिक',
    category: 'Legal Aid',
    description:
      'धारा 12(c) के तहत महिलाओं सहित पात्र व्यक्तियों को मुफ्त कानूनी परामर्श, वकील सहायता और पैरालीगल सहायता प्रदान करने वाली वैधानिक संस्था।',
    contactType: 'mixed',
    contactValue: 'हेल्पलाइन 15100 / जिला न्यायालय परिसर डीएलएसए कार्यालय',
    officialUrl: 'https://nalsa.gov.in',
    sourceOwner: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'सत्यापित कानूनी परामर्श के लिए जिला अदालत परिसर में निकटतम जिला विधिक सेवा प्राधिकरण (DLSA) कार्यालय से संपर्क करें।',
  },
  {
    id: 'res-cyber-portal',
    name: 'राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल (cybercrime.gov.in)',
    category: 'Cyber Crime',
    description:
      'महिलाओं के खिलाफ साइबर अपराधों, ऑनलाइन उत्पीड़न और आपत्तिजनक मीडिया की शिकायत दर्ज करने के लिए गृह मंत्रालय द्वारा संचालित आधिकारिक पोर्टल।',
    contactType: 'portal',
    contactValue: 'हेल्पलाइन 1930 / cybercrime.gov.in',
    officialUrl: 'https://cybercrime.gov.in',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'शैक्षिक संदर्भ के लिए आधिकारिक पोर्टल लिंक। कोई भी शिकायत दर्ज करने से पहले ब्राउज़र सुरक्षा प्रमाणपत्र की जांच करें।',
  },
];
