import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'राष्ट्रीय आपातकालीन प्रतिक्रिया (पुलिस / अग्निशमन / एम्बुलेंस)',
    number: '112',
    description: 'तत्काल आपातकालीन सहायता के लिए 24/7 एकीकृत अखिल भारतीय आपातकालीन सेवा।',
    available: '24/7 टोल-फ्री',
    isClickableEmergency: true,
  },
  {
    label: 'महिला हेल्पलाइन (मिशन शक्ति)',
    number: '181',
    description: 'संकटग्रस्त महिलाओं के लिए राष्ट्रीय कार्यक्रम हेल्पलाइन। स्थानीय केंद्र विवरण की अलग से पुष्टि आवश्यक है।',
    available: '24/7 राष्ट्रीय कार्यक्रम संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय महिला आयोग (NCW) हेल्पलाइन',
    number: '14490',
    description: 'संकटग्रस्त महिलाओं और सहायता रेफरल के लिए राष्ट्रीय महिला आयोग की आधिकारिक हेल्पलाइन।',
    available: 'राष्ट्रीय एनसीडब्ल्यू संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'नालसा (NALSA) विधिक सहायता हेल्पलाइन',
    number: '15100',
    description: 'वैधानिक अधिकारों और विधिक सहायता के लिए राष्ट्रीय टोल-फ्री हेल्पलाइन।',
    available: 'राष्ट्रीय कानूनी सहायता संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय साइबर अपराध हेल्पलाइन',
    number: '1930 (सार्वजनिक उपयोग से पहले आधिकारिक स्रोत से पुष्टि करें)',
    description: 'साइबर वित्तीय धोखाधड़ी और डिजिटल अपराधों के लिए रिपोर्टिंग हेल्पलाइन संदर्भ। रजिस्ट्री सत्यापन लंबित।',
    available: 'सत्यापन लंबित संदर्भ',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'आपातकालीन प्रतिक्रिया सहायता प्रणाली (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'नागरिकों को स्थानीय पुलिस, चिकित्सा और अग्निशमन प्रतिक्रिया दलों से सीधे जोड़ने वाला राष्ट्रव्यापी आपातकालीन मंच।',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    officialSourceUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    sourceTitle: 'Emergency Response Support System (ERSS)',
    publisher: 'गृह मंत्रालय, भारत सरकार',
    accessedAt: '2026-03-01',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '112 भारत का राष्ट्रव्यापी एकीकृत आपातकालीन नंबर है।',
    limitations: 'केवल राष्ट्रीय आपातकालीन नंबर; परिचालन प्रेषण संबंधित राज्य/केंद्र शासित प्रदेश आपातकालीन प्रतिक्रिया केंद्रों द्वारा नियंत्रित होता है।',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'आधिकारिक 24/7 राष्ट्रव्यापी आपातकालीन नंबर। सीधी आपातकालीन कॉलिंग के लिए क्लिक करने योग्य।',
    isEmergency112: true,
  },
  {
    id: 'res-whl-181',
    name: 'महिला हेल्पलाइन (181 - मिशन शक्ति)',
    category: 'National Helpline',
    description:
      'मिशन शक्ति के तहत संकटग्रस्त महिलाओं को आपातकालीन और गैर-आपातकालीन रेफरल, परामर्श और वन स्टॉप सेंटर से समन्वय प्रदान करने वाली राष्ट्रीय 24/7 टोल-फ्री हेल्पलाइन।',
    contactType: 'phone',
    contactValue: '181',
    officialUrl: 'https://missionshakti.wcd.gov.in/',
    officialSourceUrl: 'https://missionshakti.wcd.gov.in/',
    sourceTitle: 'Mission Shakti - Women Helpline 181 Guidelines',
    publisher: 'महिला एवं बाल विकास मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'महिला एवं बाल विकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd-whl',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'मिशन शक्ति महिला हेल्पलाइन 181 को सूचीबद्ध करता है और एकीकृत सहायता प्रदान करने के रूप में वन स्टॉप सेंटर योजना का वर्णन करता है।',
    limitations: 'राष्ट्रीय कार्यक्रम की जानकारी सत्यापित है; स्थानीय टेलीकॉम रूटिंग और राज्य स्तरीय उपलब्धता की अलग से पुष्टि आवश्यक है।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'राष्ट्रीय कार्यक्रम जानकारी सत्यापित; स्थानीय विवरण की अलग से पुष्टि आवश्यक है। गैर-क्लिक करने योग्य संदर्भ।',
    isEmergency112: false,
  },
  {
    id: 'res-one-stop-centres',
    name: 'सखी वन स्टॉप सेंटर (Sakhi OSC Scheme)',
    category: 'Counseling & Support',
    description:
      'हिंसा से प्रभावित महिलाओं को चिकित्सा सहायता, पुलिस सुविधा, कानूनी सहायता और अस्थायी आश्रय प्रदान करने वाले एकीकृत सहायता केंद्र।',
    contactType: 'in-person',
    contactValue: 'जिला अस्पताल / नामित ओएससी परिसर (स्थानीय स्तर पर पुष्टि करें)',
    officialUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    officialSourceUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    sourceTitle: 'One Stop Centre Scheme Guidelines & Mission Shakti',
    publisher: 'महिला एवं बाल विकास मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'महिला एवं बाल विकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd-osc',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'मिशन शक्ति वन स्टॉप सेंटर योजना को एकीकृत सहायता और साहाय्य प्रदान करने के रूप में वर्णित करता है।',
    limitations: 'राष्ट्रीय कार्यक्रम की जानकारी सत्यापित है। अलग जिला/राज्य स्रोतों के बिना किसी भी स्थानीय पते, फोन नंबर या केंद्र संपर्क को सत्यापित न मानें।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'राष्ट्रीय कार्यक्रम जानकारी सत्यापित; स्थानीय केंद्र विवरण की अलग से पुष्टि आवश्यक है। व्यक्तिगत स्थान संदर्भ।',
    isEmergency112: false,
  },
  {
    id: 'res-ncw-helpline',
    name: 'राष्ट्रीय महिला आयोग (NCW) महिला हेल्पलाइन',
    category: 'National Helpline',
    description:
      'संकटग्रस्त महिलाओं के लिए राष्ट्रीय महिला आयोग की आधिकारिक हेल्पलाइन, जो त्वरित सहायता, शिकायत निवारण और संस्थागत मार्गदर्शन की सुविधा प्रदान करती है।',
    contactType: 'phone',
    contactValue: '14490',
    officialUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    officialSourceUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    sourceTitle: 'NCW Cells - NCW Women Helpline (14490)',
    publisher: 'राष्ट्रीय महिला आयोग, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'राष्ट्रीय महिला आयोग (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'एनसीडब्ल्यू महिला हेल्पलाइन 14490 संकटग्रस्त महिलाओं और सहायता/रेफरल जानकारी के लिए एक आधिकारिक एनसीडब्ल्यू हेल्पलाइन है।',
    limitations: 'केवल राष्ट्रीय एनसीडब्ल्यू हेल्पलाइन विवरण और 14490; असमर्थित परिचालन विवरण प्रदर्शित न करें।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'सत्यापित राष्ट्रीय संपर्क। टेलीफोन नंबर गैर-क्लिक करने योग्य संदर्भ के रूप में है। फोन से सीधे 14490 डायल करें।',
    isEmergency112: false,
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA) विधिक सहायता हेल्पलाइन',
    category: 'Legal Aid',
    description:
      'विधिक सेवा प्राधिकरण अधिनियम की धारा 12(c) के तहत महिलाओं सहित पात्र व्यक्तियों को मुफ्त कानूनी परामर्श, वकील सहायता और वैधानिक मार्गदर्शन प्रदान करने वाली संस्था।',
    contactType: 'phone',
    contactValue: '15100',
    officialUrl: 'https://nalsa.gov.in/',
    officialSourceUrl: 'https://nalsa.gov.in/',
    sourceTitle: 'National Legal Services Authority Legal Aid Portal & FAQs',
    publisher: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA)',
    accessedAt: '2026-10-08',
    sourceOwner: 'राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'नालसा (NALSA) 15100 को अपनी टोल-फ्री विधिक सहायता हेल्पलाइन के रूप में पहचानता है।',
    limitations: 'राष्ट्रीय नालसा कानूनी सहायता हेल्पलाइन और सामान्य कानूनी सहायता विवरण। स्थानीय वकील नियुक्ति के लिए जिला डीएलएसए से समन्वय आवश्यक है।',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'सत्यापित राष्ट्रीय संपर्क। टेलीफोन नंबर गैर-क्लिक करने योग्य संदर्भ के रूप में है। फोन से सीधे 15100 डायल करें।',
    isEmergency112: false,
  },
  {
    id: 'res-cyber-portal',
    name: 'राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल (cybercrime.gov.in)',
    category: 'Cyber Crime',
    description:
      'महिलाओं के खिलाफ साइबर अपराधों, ऑनलाइन उत्पीड़न और आपत्तिजनक मीडिया की शिकायत दर्ज करने के लिए गृह मंत्रालय द्वारा संचालित आधिकारिक पोर्टल।',
    contactType: 'portal',
    contactValue: 'हेल्पलाइन 1930 / cybercrime.gov.in',
    officialUrl: 'https://cybercrime.gov.in',
    officialSourceUrl: 'https://cybercrime.gov.in',
    sourceTitle: 'National Cyber Crime Reporting Portal (NCRP)',
    publisher: 'गृह मंत्रालय, भारत सरकार',
    accessedAt: '2026-02-15',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-02-15',
    nextReviewDueDate: '2026-08-15',
    verificationStatus: 'needs-verification',
    verificationScope: 'pending',
    verifiedClaim: 'एनसीआरपी पोर्टल और 1930 हेल्पलाइन रिकॉर्ड के लिए आधिकारिक स्रोत रजिस्ट्री सत्यापन लंबित है।',
    limitations: 'लॉन्च करने से पहले इस संपर्क जानकारी को आधिकारिक स्रोत से सत्यापित करें।',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'सार्वजनिक उपयोग से पहले आधिकारिक स्रोत से पुष्टि करें। शैक्षिक संदर्भ के लिए आधिकारिक पोर्टल लिंक।',
    isEmergency112: false,
  },
];
