import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'National Emergency Response (Police / Fire / Ambulance)',
    number: '112',
    description: 'Unified 24/7 nationwide emergency service for immediate emergency dispatch.',
    available: '24/7 Toll-Free',
    isClickableEmergency: true,
  },
  {
    label: 'Women Helpline (National)',
    number: '1091 (Verify from official source before public launch)',
    description: 'Helpline reference for women in distress. Subject to administrative verification.',
    available: 'Toll-Free Reference',
    isClickableEmergency: false,
  },
  {
    label: 'National Cyber Crime Helpline',
    number: '1930 (Verify from official source before public launch)',
    description: 'Government reporting helpline for cyber financial fraud and digital abuse.',
    available: 'National Reference',
    isClickableEmergency: false,
  },
  {
    label: 'National Commission for Women (NCW)',
    number: '7827170170 (Verify from official source before public launch)',
    description: 'NCW helpline contact reference for counseling and procedural guidance.',
    available: 'Helpdesk Reference',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'Emergency Response Support System (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'Nationwide emergency platform linking citizens directly to local police, medical, and fire dispatch teams for immediate crisis response.',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://112.gov.in',
    sourceOwner: 'Ministry of Home Affairs, Government of India',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    verificationStatus: 'verified',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'Official 24/7 nationwide emergency number. Clickable for direct emergency calling.',
    isEmergency112: true,
  },
  {
    id: 'res-one-stop-centres',
    name: 'Sakhi One Stop Centres (OSC)',
    category: 'Counseling & Support',
    description:
      'Centrally sponsored scheme establishing integrated support centres across districts to provide medical aid, police facilitation, legal aid, and temporary shelter.',
    contactType: 'in-person',
    contactValue: 'District Hospital / Designated OSC Complex',
    officialUrl: 'https://wcd.nic.in',
    sourceOwner: 'Ministry of Women and Child Development (MWCD)',
    sourceId: 'src-mowcd',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'Verify exact local district centre address and contacts from official district administration before visit.',
  },
  {
    id: 'res-ncw-helpline',
    name: 'National Commission for Women (NCW) 24/7 Helpline',
    category: 'National Helpline',
    description:
      'National commission helpline dedicated to facilitating intervention, counseling, and grievance redressal for women facing violence or rights violations.',
    contactType: 'phone',
    contactValue: '7827170170 (Placeholder - Verify before launch)',
    officialUrl: 'http://ncw.nic.in',
    sourceOwner: 'National Commission for Women (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'Non-clickable placeholder. Verify with official NCW portal prior to non-emergency engagement.',
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'National Legal Services Authority (NALSA) / DLSA Clinics',
    category: 'Legal Aid',
    description:
      'Statutory legal services offering free legal consultation, advocate assignment, and paralegal support to eligible persons including women under Section 12(c).',
    contactType: 'mixed',
    contactValue: 'Helpline 15100 / District Court Complex DLSA Offices',
    officialUrl: 'https://nalsa.gov.in',
    sourceOwner: 'National Legal Services Authority',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'Visit your nearest District Legal Services Authority (DLSA) office in the district court complex for verified counsel.',
  },
  {
    id: 'res-cyber-portal',
    name: 'National Cyber Crime Reporting Portal (cybercrime.gov.in)',
    category: 'Cyber Crime',
    description:
      'Official citizen reporting portal maintained by MHA for lodging complaints regarding cyber crimes, online harassment, and objectionable media against women.',
    contactType: 'portal',
    contactValue: 'Helpline 1930 / cybercrime.gov.in',
    officialUrl: 'https://cybercrime.gov.in',
    sourceOwner: 'Ministry of Home Affairs, Government of India',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'Official portal link provided for educational reference. Verify browser SSL certificate before submitting any report.',
  },
];
