import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'National Emergency Response (Police / Fire / Ambulance)',
    number: '112',
    description: 'Unified 24/7 nationwide emergency service for immediate emergency dispatch.',
    available: '24/7 Toll-Free Emergency',
    isClickableEmergency: true,
  },
  {
    label: 'Women Helpline (Mission Shakti)',
    number: '181',
    description: 'National 24/7 toll-free support and referral helpline for women in distress.',
    available: '24/7 National Support',
    isClickableEmergency: false,
  },
  {
    label: 'NCW Women Helpline',
    number: '14490',
    description: 'Official National Commission for Women helpline for women facing violence or distress.',
    available: 'National Support & Referral',
    isClickableEmergency: false,
  },
  {
    label: 'NALSA Legal Aid Helpline',
    number: '15100',
    description: 'Toll-free national legal aid helpline identifying statutory entitlements and DLSA clinics.',
    available: 'Free Legal Aid & Guidance',
    isClickableEmergency: false,
  },
  {
    label: 'National Cyber Crime Helpline (Online Financial Fraud)',
    number: '1930',
    description: 'Official national cybercrime helpline for reporting online financial scams and fraud.',
    available: 'Financial Cyber Fraud Assistance',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'Emergency Response Support System (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'Nationwide emergency platform linking citizens directly to local police, medical, and fire dispatch teams for immediate crisis response.',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    officialSourceUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    sourceTitle: 'Emergency Response Support System (ERSS)',
    publisher: 'Ministry of Home Affairs, Government of India',
    accessedAt: '2026-03-01',
    sourceOwner: 'Ministry of Home Affairs, Government of India',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '112 is India’s nationwide unified emergency number.',
    limitations: 'National emergency number only; operational dispatch is handled by respective State/UT Emergency Response Centres.',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'Official 24/7 nationwide emergency number. For life-threatening emergencies, dial 112 immediately.',
    isEmergency112: true,
  },
  {
    id: 'res-whl-181',
    name: 'Women Helpline (181 - Mission Shakti)',
    category: 'National Helpline',
    description:
      'National 24/7 toll-free helpline providing emergency and non-emergency referral, counseling, and integration with One Stop Centres under Mission Shakti.',
    contactType: 'phone',
    contactValue: '181',
    officialUrl: 'https://missionshakti.wcd.gov.in/',
    officialSourceUrl: 'https://missionshakti.wcd.gov.in/',
    sourceTitle: 'Mission Shakti - Women Helpline 181 Guidelines',
    publisher: 'Ministry of Women and Child Development, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'Ministry of Women and Child Development (MWCD)',
    sourceId: 'src-mowcd-whl',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'Mission Shakti lists Women Helpline 181 and describes the One Stop Centre scheme as providing integrated support and assistance.',
    limitations: 'National programme information verified; local routing, state telecom operational availability, and district response times require separate verification.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'National support helpline under Mission Shakti. In life-threatening emergencies, always dial 112 directly.',
    isEmergency112: false,
  },
  {
    id: 'res-ncw-helpline',
    name: 'National Commission for Women (NCW) Women Helpline',
    category: 'National Helpline',
    description:
      'Official NCW helpline for women in distress, facilitating intervention, counseling, and grievance redressal for women facing violence or rights violations.',
    contactType: 'phone',
    contactValue: '14490',
    officialUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    officialSourceUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    sourceTitle: 'NCW Cells - NCW Women Helpline (14490)',
    publisher: 'National Commission for Women, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'National Commission for Women (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'NCW Women Helpline 14490 is an official NCW helpline for women in distress and support/referral information.',
    limitations: 'National NCW helpline description and 14490 only. Does not promise guaranteed immediate field intervention or outcomes.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'National support and referral helpline. Dial 14490 directly for guidance and complaint facilitation.',
    isEmergency112: false,
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'National Legal Services Authority (NALSA) Legal Aid Helpline',
    category: 'Legal Aid',
    description:
      'Statutory legal services offering free legal consultation, advocate assignment, and paralegal support to eligible persons including women under Section 12(c).',
    contactType: 'phone',
    contactValue: '15100',
    officialUrl: 'https://nalsa.gov.in/',
    officialSourceUrl: 'https://nalsa.gov.in/',
    sourceTitle: 'National Legal Services Authority Legal Aid Portal & FAQs',
    publisher: 'National Legal Services Authority (NALSA)',
    accessedAt: '2026-10-08',
    sourceOwner: 'National Legal Services Authority (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'NALSA identifies 15100 as its toll-free legal-aid helpline.',
    limitations: 'National NALSA legal-aid helpline and general legal-aid description. Court advocate assignment requires coordination with jurisdictional DLSA clinics.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'National legal aid guidance helpline. Does not promise a specific legal outcome or immediate representation.',
    isEmergency112: false,
  },
  {
    id: 'res-cyber-portal',
    name: 'National Cyber Crime Helpline (1930 - Financial Fraud)',
    category: 'Cyber Crime',
    description:
      'Official citizen helpline operated under Ministry of Home Affairs dedicated to citizen reporting of online financial cyber fraud and unauthorized transactions.',
    contactType: 'phone',
    contactValue: '1930',
    officialUrl: 'https://cybercrime.gov.in',
    officialSourceUrl: 'https://cybercrime.gov.in',
    sourceTitle: 'Citizen Financial Cyber Fraud Reporting System (1930)',
    publisher: 'Ministry of Home Affairs, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'Ministry of Home Affairs, Government of India',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '1930 is the national cybercrime helpline dedicated to citizen financial cyber fraud reporting.',
    limitations: 'Helpline specifically dedicated to online financial fraud incidents. Not a universal emergency dispatch number; not the investigative route for every non-financial cyber offense.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'Official helpline for reporting financial cyber fraud. For immediate physical danger or general emergency, call 112.',
    isEmergency112: false,
  },
  {
    id: 'res-one-stop-centres',
    name: 'Sakhi One Stop Centres (OSC Scheme)',
    category: 'Counseling & Support',
    description:
      'Centrally sponsored scheme establishing integrated district facilities to provide medical aid, police facilitation, legal counseling, and temporary shelter.',
    contactType: 'in-person',
    contactValue: 'District Hospital / Designated OSC Complex (Verify locally)',
    officialUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    officialSourceUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    sourceTitle: 'One Stop Centre Scheme Guidelines & Mission Shakti',
    publisher: 'Ministry of Women and Child Development, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'Ministry of Women and Child Development (MWCD)',
    sourceId: 'src-mowcd-osc',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'Mission Shakti describes the One Stop Centre scheme as providing integrated support and assistance.',
    limitations: 'National programme information verified. District address, phone number, and operating hours must remain separately verified.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'In-person facility reference. Please verify exact local district centre address and operational hours before visiting.',
    isEmergency112: false,
  },
  {
    id: 'res-local-counseling',
    name: 'District Counseling & Family Guidance Clinic',
    category: 'Counseling & Support',
    description:
      'District administration reference for local family counseling and dispute mediation cells.',
    contactType: 'phone',
    contactValue: 'District Cell Reference (Pending verification)',
    officialUrl: '',
    officialSourceUrl: '',
    sourceTitle: 'District Administrative Directory Reference',
    publisher: 'State / District Administration',
    accessedAt: '2026-02-15',
    sourceOwner: 'District Administration',
    sourceId: 'src-district-ref',
    lastVerifiedDate: '2026-02-15',
    nextReviewDueDate: '2026-08-15',
    verificationStatus: 'needs-verification',
    verificationScope: 'pending',
    verifiedClaim: '',
    limitations: 'Local contact details undergoing administrative verification. Do not rely without separate confirmation.',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'Reference information pending verification. Verify from official source before public launch.',
    isEmergency112: false,
  },
];
