import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'National Emergency Response (Police / Fire / Ambulance)',
    number: '112',
    description: 'Unified 24/7 nationwide emergency service for immediate emergency dispatch.',
    available: '24/7 Toll-Free',
    isClickableEmergency: true,
  },
  {
    label: 'Women Helpline (Mission Shakti)',
    number: '181',
    description: 'National programme helpline for women in distress. Local centre details require separate verification.',
    available: '24/7 National Programme Reference',
    isClickableEmergency: false,
  },
  {
    label: 'NCW Women Helpline',
    number: '14490',
    description: 'Official National Commission for Women helpline for women in distress and support referrals.',
    available: 'National NCW Reference',
    isClickableEmergency: false,
  },
  {
    label: 'NALSA Legal Aid Helpline',
    number: '15100',
    description: 'Toll-free national legal aid helpline identifying statutory entitlements and DLSA assistance.',
    available: 'National Legal Aid Reference',
    isClickableEmergency: false,
  },
  {
    label: 'National Cyber Crime Helpline',
    number: '1930 (Verify from official source before public launch)',
    description: 'Reporting helpline reference for cyber financial fraud and digital abuse. Pending registry verification.',
    available: 'Pending Verification Reference',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'Emergency Response Support System (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'Nationwide emergency platform linking citizens directly to local police, medical, and fire dispatch teams for immediate crisis response.',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    officialSourceUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    sourceTitle: 'Emergency Response Support System (ERSS)',
    publisher: 'Ministry of Home Affairs, Government of India',
    accessedAt: '2026-03-01',
    sourceOwner: 'Ministry of Home Affairs, Government of India',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '112 is India’s nationwide unified emergency number.',
    limitations: 'National emergency number only; operational dispatch is handled by respective State/UT Emergency Response Centres.',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'Official 24/7 nationwide emergency number. Clickable for direct emergency calling.',
    isEmergency112: true,
  },
  {
    id: 'res-whl-181',
    name: 'Women Helpline (181 - Mission Shakti)',
    category: 'National Helpline',
    description:
      'National 24/7 toll-free helpline providing emergency and non-emergency referral, counseling, and integration with One Stop Centres under Mission Shakti.',
    contactType: 'phone',
    contactValue: '181',
    officialUrl: 'https://missionshakti.wcd.gov.in/',
    officialSourceUrl: 'https://missionshakti.wcd.gov.in/',
    sourceTitle: 'Mission Shakti - Women Helpline 181 Guidelines',
    publisher: 'Ministry of Women and Child Development, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'Ministry of Women and Child Development (MWCD)',
    sourceId: 'src-mowcd-whl',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'Mission Shakti lists Women Helpline 181 and describes the One Stop Centre scheme as providing integrated support and assistance.',
    limitations: 'National programme information verified; local routing, state telecom operational availability, and district response times require separate verification.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'National programme information verified; local centre details require separate verification. Non-clickable reference.',
    isEmergency112: false,
  },
  {
    id: 'res-one-stop-centres',
    name: 'Sakhi One Stop Centres (OSC Scheme)',
    category: 'Counseling & Support',
    description:
      'Centrally sponsored scheme establishing integrated district facilities to provide medical aid, police facilitation, legal counseling, and temporary shelter.',
    contactType: 'in-person',
    contactValue: 'District Hospital / Designated OSC Complex (Verify locally)',
    officialUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    officialSourceUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    sourceTitle: 'One Stop Centre Scheme Guidelines & Mission Shakti',
    publisher: 'Ministry of Women and Child Development, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'Ministry of Women and Child Development (MWCD)',
    sourceId: 'src-mowcd-osc',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'Mission Shakti describes the One Stop Centre scheme as providing integrated support and assistance.',
    limitations: 'National programme information verified. Do not mark any district address, local phone number, office hours, or specific centre contact as verified without separate district/state sources.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'National programme information verified; local centre details require separate verification. In-person location reference.',
    isEmergency112: false,
  },
  {
    id: 'res-ncw-helpline',
    name: 'National Commission for Women (NCW) Women Helpline',
    category: 'National Helpline',
    description:
      'Official NCW helpline for women in distress, facilitating intervention, counseling, and grievance redressal for women facing violence or rights violations.',
    contactType: 'phone',
    contactValue: '14490',
    officialUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    officialSourceUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    sourceTitle: 'NCW Cells - NCW Women Helpline (14490)',
    publisher: 'National Commission for Women, Government of India',
    accessedAt: '2026-10-08',
    sourceOwner: 'National Commission for Women (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'NCW Women Helpline 14490 is an official NCW helpline for women in distress and support/referral information.',
    limitations: 'National NCW helpline description and 14490 only. Do not display unsupported operating details.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'Verified national contact. Telephone number rendered as non-clickable reference. Dial 14490 directly from phone.',
    isEmergency112: false,
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'National Legal Services Authority (NALSA) Legal Aid Helpline',
    category: 'Legal Aid',
    description:
      'Statutory legal services offering free legal consultation, advocate assignment, and paralegal support to eligible persons including women under Section 12(c).',
    contactType: 'phone',
    contactValue: '15100',
    officialUrl: 'https://nalsa.gov.in/',
    officialSourceUrl: 'https://nalsa.gov.in/',
    sourceTitle: 'National Legal Services Authority Legal Aid Portal & FAQs',
    publisher: 'National Legal Services Authority (NALSA)',
    accessedAt: '2026-10-08',
    sourceOwner: 'National Legal Services Authority (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'NALSA identifies 15100 as its toll-free legal-aid helpline.',
    limitations: 'National NALSA legal-aid helpline and general legal-aid description. Court advocate assignment requires coordination with jurisdictional DLSA clinics.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'Verified national contact. Telephone number rendered as non-clickable reference. Dial 15100 directly from phone.',
    isEmergency112: false,
  },
  {
    id: 'res-cyber-portal',
    name: 'National Cyber Crime Reporting Portal (cybercrime.gov.in)',
    category: 'Cyber Crime',
    description:
      'Official citizen reporting portal maintained by MHA for lodging complaints regarding cyber crimes, online harassment, and objectionable media against women.',
    contactType: 'portal',
    contactValue: 'Helpline 1930 / cybercrime.gov.in',
    officialUrl: 'https://cybercrime.gov.in',
    officialSourceUrl: 'https://cybercrime.gov.in',
    sourceTitle: 'National Cyber Crime Reporting Portal (NCRP)',
    publisher: 'Ministry of Home Affairs, Government of India',
    accessedAt: '2026-02-15',
    sourceOwner: 'Ministry of Home Affairs, Government of India',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-02-15',
    nextReviewDueDate: '2026-08-15',
    verificationStatus: 'needs-verification',
    verificationScope: 'pending',
    verifiedClaim: 'Pending official source registry verification for NCRP portal and 1930 helpline records.',
    limitations: 'Verify this contact information from an official source before launch.',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'Verify from official source before public launch. Official portal link provided for educational reference.',
    isEmergency112: false,
  },
];
