import { TopicItem } from '@/types/content';

export const topicsData: TopicItem[] = [
  {
    id: 'topic-domestic-violence',
    slug: 'domestic-violence',
    title: 'Domestic Violence & Household Safety',
    category: 'domestic',
    summary: 'Awareness on recognizing patterns of abuse in shared households, civil protections, and emergency steps.',
    plainIntroduction:
      'Domestic violence can affect women across diverse circumstances. Under Indian legal awareness frameworks, it is understood as abusive behaviour within a shared household or domestic relationship. General information on this topic focuses on safety planning, civil protection avenues, and verified support services.',
    whatItMayInclude: [
      'Physical aggression or threats of bodily harm.',
      'Emotional, verbal abuse, insults, or constant humiliation.',
      'Economic deprivation, withholding money, basic necessities, or preventing employment.',
      'Sexual coercion or non-consensual acts within a relationship.',
      'Forced isolation from friends, family, or support networks.',
    ],
    examples: [
      'An individual being denied access to family financial resources or personal identity documents.',
      'Repeated threats of abandonment, physical harm, or emotional manipulation.',
      'Being forcefully confined or restricted from contacting external relatives.',
    ],
    saferNextSteps: [
      'If you are in immediate physical danger, prioritize leaving the immediate vicinity if safe, and contact emergency services (112).',
      'Identify a trusted family member, neighbor, or friend who can assist if an urgent situation arises.',
      'Consider keeping essential personal identification and necessary medicine in an accessible location, if safe.',
      'Consult verified institutional resources such as One Stop Centres (OSC) or legal aid clinics for structured guidance.',
    ],
    evidenceAndRecordsSafety: [
      'Maintain personal documentation of dates, times, or medical prescriptions only if doing so does not compromise your safety.',
      'Do not engage in hazardous confrontation to gather proof.',
      'Never attempt secret recording if it puts your physical safety at risk.',
      'Keep copies of necessary official papers with a trusted contact or in a secure location if feasible.',
    ],
    whereToLookForHelp: [
      'Emergency Response Support System: 112 (National 24/7 emergency dispatch).',
      'District Protection Officers and Sakhi One Stop Centres established by the Ministry of Women & Child Development.',
      'District Legal Services Authority (DLSA) for free legal information.',
    ],
    relatedLawIds: ['law-dv-act-2005'],
    relatedResourceIds: ['res-er-112', 'res-one-stop-centres', 'res-nalsa-legal-aid'],
    relatedGuideSlugs: ['workplace-harassment-steps', 'online-abuse-steps'],
    sourceIds: ['src-mowcd', 'src-nalsa'],
    tags: ['Domestic Safety', 'PWDVA', 'Protection Orders', 'Household Rights'],
    disclaimerText:
      'This awareness content provides general educational information and is not formal legal counsel, clinical therapy, or emergency dispatch. For immediate safety risks, call 112.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-sexual-harassment',
    slug: 'sexual-harassment',
    title: 'Sexual Harassment Awareness',
    category: 'rights',
    summary: 'General educational awareness on unwelcome sexual behavior, personal boundaries, and institutional redressal.',
    plainIntroduction:
      'Sexual harassment encompasses unwelcome words, gestures, demands, or conduct of a sexual nature. Awareness education emphasizes recognizing unwelcome conduct, understanding dignity protections, and reviewing institutional reporting channels.',
    whatItMayInclude: [
      'Unwelcome physical touch, brushing against someone, or invasion of personal space.',
      'Sexually suggestive remarks, inappropriate comments on appearance, or intrusive questioning.',
      'Unsolicited sexual requests, messages, or display of inappropriate material.',
      'Implied promises of preferential treatment or threats of detrimental treatment tied to sexual conduct.',
    ],
    examples: [
      'A person repeatedly sending suggestive messages despite clear requests to stop.',
      'Inappropriate touching in transit, public spaces, or educational institutions.',
      'Unwanted physical gestures or sexually charged comments in social gatherings.',
    ],
    saferNextSteps: [
      'Clearly and firmly communicate that the behavior is unwelcome, if you assess it is safe to do so.',
      'Move toward public, well-lit, or populated areas if the situation occurs in transit or public spaces.',
      'Share details with trusted individuals or institutional grievance officers.',
      'In emergency situations or physical threats, contact 112 immediately.',
    ],
    evidenceAndRecordsSafety: [
      'Note dates, times, witnesses, and details of communications if safe to do so.',
      'Preserve digital text exchanges or timestamps without modifying the originals.',
      'Do not attempt dangerous confrontations or secret recordings that could escalate risk.',
    ],
    whereToLookForHelp: [
      'National Emergency Helpline: 112.',
      'Institutional grievance desks or women helpdesks at local police stations.',
      'Legal Services Authorities (NALSA/DLSA) for guidance on procedural protections.',
    ],
    relatedLawIds: ['law-posh-act-2013', 'law-bns-placeholder'],
    relatedResourceIds: ['res-er-112', 'res-ncw-helpline', 'res-nalsa-legal-aid'],
    relatedGuideSlugs: ['workplace-harassment-steps'],
    sourceIds: ['src-ncw', 'src-nalsa'],
    tags: ['Harassment', 'Bodily Autonomy', 'Dignity', 'Public Safety'],
    disclaimerText:
      'Educational awareness only. Specific remedies depend on jurisdiction, context, and official legal procedures. It does not replace professional legal or crisis support.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-stalking',
    slug: 'stalking',
    title: 'Stalking & Physical Tracking',
    category: 'rights',
    summary: 'Recognizing persistent, unwanted physical following, surveillance, and safety measures.',
    plainIntroduction:
      'Stalking involves repeated, unwanted attempts to follow, monitor, contact, or watch a person, creating feelings of distress or danger. Awareness guidelines focus on immediate safety precautions, route variation, and engaging official help.',
    whatItMayInclude: [
      'Following a person during their daily commute, to home, or to their workplace.',
      'Loitering outside a person’s residence, school, or office building.',
      'Repeatedly leaving unwanted notes, gifts, or messages.',
      'Attempting to gather personal schedule details from neighbors, colleagues, or peers.',
    ],
    examples: [
      'An individual consistently appearing at transit stops along a daily commuting route.',
      'Receiving repeated unwanted visits at workplace entrances.',
      'A person monitoring daily movement routines without consent.',
    ],
    saferNextSteps: [
      'If you believe you are being followed, move immediately into a crowded, well-lit public establishment or police outpost.',
      'Never confront a suspected stalker directly or attempt to isolate yourself with them.',
      'Inform trusted family members, colleagues, or building security about your safety concerns.',
      'Consider varying your daily routes and commute timings if feasible.',
      'Contact emergency services (112) if you feel in immediate danger.',
    ],
    evidenceAndRecordsSafety: [
      'Keep a factual log of dates, times, vehicle registration details (if observed safely), and locations.',
      'Never place yourself in danger or attempt covert operations to capture photographs or video.',
      'Rely on official CCTV surveillance footage requested through law enforcement channels when safe.',
    ],
    whereToLookForHelp: [
      'Emergency Response Support System: 112.',
      'Nearest jurisdictional police station or Women Help Desk.',
      'District Legal Services Authority (DLSA).',
    ],
    relatedLawIds: ['law-bns-placeholder'],
    relatedResourceIds: ['res-er-112', 'res-ncw-helpline'],
    relatedGuideSlugs: ['workplace-harassment-steps'],
    sourceIds: ['src-mha-erss', 'src-ncw'],
    tags: ['Stalking', 'Physical Safety', 'Commute Safety', 'Surveillance'],
    disclaimerText:
      'General safety awareness only. If in immediate danger, prioritize moving to a safe public space and call emergency services (112).',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-cyberstalking',
    slug: 'cyberstalking',
    title: 'Cyberstalking & Digital Monitoring',
    category: 'cyber',
    summary: 'Understanding online surveillance, persistent digital harassment, and safe cyber hygiene.',
    plainIntroduction:
      'Cyberstalking involves using the internet, messaging applications, social media, or electronic tracking devices to systematically harass, monitor, or threaten someone. Informational resources highlight digital privacy habits and evidence logging.',
    whatItMayInclude: [
      'Flooding email, chat, or social media accounts with unwanted messages from multiple accounts.',
      'Monitoring online activities, likes, comments, and tagging mutual contacts.',
      'Using spyware, unauthorized location sharing, or Bluetooth trackers to follow movement.',
      'Threatening public disclosure of personal communications or private data.',
    ],
    examples: [
      'An individual creating new social media handles to message someone after being blocked repeatedly.',
      'Someone posting threatening comments on every public photo or video shared.',
      'Receiving notifications that an unknown Bluetooth tracker or device is moving with you.',
    ],
    saferNextSteps: [
      'Review and restrict account privacy settings across all digital and social platforms.',
      'Audit connected devices, active sessions, and location sharing permissions on your phone.',
      'Use platform tools to report and block abusive accounts after securing evidence safely.',
      'Avoid sharing live locations, check-ins, or daily routine schedules publicly online.',
    ],
    evidenceAndRecordsSafety: [
      'Take uncropped screenshots showing sender handles, dates, times, and message text before blocking.',
      'Save full profile URLs of offending profiles.',
      'Keep copies in a separate, password-protected digital drive or backup.',
      'Do not engage in arguments or send money under threats.',
    ],
    whereToLookForHelp: [
      'National Cyber Crime Reporting Portal: cybercrime.gov.in (Official Government Portal).',
      'National Emergency Helpline: 112 (if threats involve immediate physical danger).',
      'Platform trust and safety moderation teams.',
    ],
    relatedLawIds: ['law-it-act-2000', 'law-bns-placeholder'],
    relatedResourceIds: ['res-er-112', 'res-cyber-portal'],
    relatedGuideSlugs: ['online-abuse-steps'],
    sourceIds: ['src-mha-ncrp', 'src-ncw'],
    tags: ['Cyberstalking', 'Digital Safety', 'Privacy', 'Online Harassment'],
    disclaimerText:
      'General digital safety awareness only. For cyber crime reporting, visit the official government portal at cybercrime.gov.in.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-dowry-harassment',
    slug: 'dowry-harassment',
    title: 'Dowry-Related Harassment & Marital Safety',
    category: 'domestic',
    summary: 'Educational awareness on the prohibition of dowry demands, statutory safeguards, and support avenues.',
    plainIntroduction:
      'Demanding, giving, or taking dowry is prohibited under Indian statutory frameworks. Harassment or cruelty associated with property demands within marriage is recognized under criminal and civil protective provisions. Awareness focuses on rights, mediation resources, and safety planning.',
    whatItMayInclude: [
      'Demands for money, vehicles, jewelry, or property before, during, or after marriage.',
      'Verbal abuse, harassment, or physical intimidation tied to unmet marital demands.',
      'Coercion targeting a woman’s parents or relatives for financial assets.',
      'Withholding personal belongings or stridhan (a woman’s personal gifts and property).',
    ],
    examples: [
      'Being pressured or subjected to hostility to demand property from maternal family members.',
      'Denial of access to personal jewelry, wedding gifts, or financial documents.',
    ],
    saferNextSteps: [
      'Prioritize your physical safety; if at risk of harm, move to a secure location if possible and contact 112.',
      'Maintain an independent inventory of your personal assets and stridhan documents if safe.',
      'Reach out to family welfare committees, DLSA legal clinics, or designated women helpdesks.',
      'Seek institutional counseling and legal aid to understand statutory protection options.',
    ],
    evidenceAndRecordsSafety: [
      'Keep copies of receipts, bank transactions, or communication records in a safe location away from the shared residence if safe.',
      'Do not engage in dangerous arguments or risk personal safety to retrieve documents.',
    ],
    whereToLookForHelp: [
      'Emergency Response Support System: 112.',
      'Sakhi One Stop Centres (OSC) for shelter, legal advice, and medical aid.',
      'District Legal Services Authority (DLSA) for free legal aid under Section 12.',
      'State Women Commissions and NCW Helpdesk.',
    ],
    relatedLawIds: ['law-dowry-prohibition-1961', 'law-dv-act-2005'],
    relatedResourceIds: ['res-er-112', 'res-one-stop-centres', 'res-nalsa-legal-aid'],
    relatedGuideSlugs: ['workplace-harassment-steps'],
    sourceIds: ['src-mowcd', 'src-nalsa'],
    tags: ['Dowry Prohibition', 'Marital Safety', 'Stridhan', 'Domestic Rights'],
    disclaimerText:
      'This portal provides educational awareness only. It does not provide legal representation or file formal complaints.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-fake-profiles-impersonation',
    slug: 'fake-profiles-impersonation',
    title: 'Fake Profiles & Online Impersonation',
    category: 'cyber',
    summary: 'Recognizing identity theft, unauthorized profile creation, and official reporting procedures.',
    plainIntroduction:
      'Online impersonation occurs when an unauthorized person creates social media profiles, email accounts, or listings using another individual’s name, photographs, or contact information. Educational guidance covers evidence retention and platform reporting.',
    whatItMayInclude: [
      'Creating duplicate social accounts using a person’s real photos and name.',
      'Posting false, defamatory, or explicit content under someone else’s identity.',
      'Sharing a person’s phone number or address on public forums without consent.',
      'Sending fraudulent or abusive messages to peers while posing as the victim.',
    ],
    examples: [
      'A fraudulent account created on a social platform messaging friends to solicit money or defamatory exchanges.',
      'Personal contact details published on public classifieds leading to unsolicited calls.',
    ],
    saferNextSteps: [
      'Document the fraudulent profile link (URL) and capture screenshots showing username and bio.',
      'Report the account directly to the hosting platform under "Impersonation / Fake Account" categories.',
      'Alert friends and close contacts not to interact with or send funds to the fake profile.',
      'File an official report on the National Cyber Crime Reporting Portal (cybercrime.gov.in).',
    ],
    evidenceAndRecordsSafety: [
      'Record the full web URL (not just display handle) of the fake account.',
      'Capture clear screenshots of posted content, comments, or direct messages.',
      'Do not engage or converse with the impostor.',
    ],
    whereToLookForHelp: [
      'National Cyber Crime Reporting Portal: cybercrime.gov.in.',
      'Platform grievance and reporting officers.',
      'Cyber crime police stations at district level.',
    ],
    relatedLawIds: ['law-it-act-2000'],
    relatedResourceIds: ['res-cyber-portal', 'res-er-112'],
    relatedGuideSlugs: ['online-abuse-steps'],
    sourceIds: ['src-mha-ncrp', 'src-meity'],
    tags: ['Impersonation', 'Identity Theft', 'Social Media', 'Cyber Safety'],
    disclaimerText:
      'Informational guidance on digital security. For administrative takedown and legal reporting, use official platform and government mechanisms.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-image-based-abuse',
    slug: 'image-based-abuse',
    title: 'Image-Based Abuse & Non-Consensual Media',
    category: 'cyber',
    summary: 'Safeguards, evidence management, and reporting for non-consensual image sharing, morphing, and extortion.',
    plainIntroduction:
      'Non-consensual creation, sharing, morphing, or threatening distribution of intimate or private images is a severe offense. Awareness guidance focuses on avoiding extortion traps, preserving unedited digital proof, and accessing specialized reporting tools.',
    whatItMayInclude: [
      'Sharing or threatening to share private photographs or video recordings without consent.',
      'Creating digitally altered, morphed, or artificial deepfake images.',
      'Demanding money, favors, or compliance under threat of circulating personal media (sextortion).',
      'Capturing unauthorized images in private spaces or transit.',
    ],
    examples: [
      'Receiving messages demanding funds to prevent intimate media from being sent to contacts.',
      'Finding altered or edited photographs circulating in messaging groups without authorization.',
    ],
    saferNextSteps: [
      'Do not transfer money or comply with extortion demands; compliance often leads to further extortion.',
      'Preserve digital evidence safely before deleting chats or blocking numbers.',
      'Report immediately on cybercrime.gov.in under the specialized section for women/children media abuse.',
      'Use platform emergency reporting mechanisms for non-consensual intimate imagery.',
    ],
    evidenceAndRecordsSafety: [
      'Take full uncropped screenshots including phone numbers, profile handles, and system timestamps.',
      'Never edit or modify the screenshot files.',
      'Store proof on a secure external device or trusted offline backup.',
    ],
    whereToLookForHelp: [
      'National Cyber Crime Reporting Portal (cybercrime.gov.in - Anonymous reporting option available for objectionable media).',
      'Cyber Crime Helpline: 1930 (Official MHA Cyber Helpline).',
      'Emergency Services: 112 (if immediate extortion or physical threats exist).',
    ],
    relatedLawIds: ['law-it-act-2000', 'law-bns-placeholder'],
    relatedResourceIds: ['res-cyber-portal', 'res-er-112'],
    relatedGuideSlugs: ['online-abuse-steps'],
    sourceIds: ['src-mha-ncrp', 'src-meity'],
    tags: ['Image Abuse', 'Non-Consensual Media', 'Deepfakes', 'Cyber Extortion'],
    disclaimerText:
      'Educational awareness on digital rights. Never negotiate with extortionists. Seek official help via government portals.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-online-privacy-consent',
    slug: 'online-privacy-consent',
    title: 'Online Privacy, App Permissions & Consent',
    category: 'cyber',
    summary: 'Best practices for securing smartphone permissions, account safety, two-factor authentication, and digital boundaries.',
    plainIntroduction:
      'Protecting personal privacy online involves managing digital footprints, understanding application permissions, maintaining secure account credentials, and establishing clear consent boundaries across digital communications.',
    whatItMayInclude: [
      'Applications requesting unnecessary access to camera, microphone, contacts, or background location.',
      'Sharing account credentials, passwords, or unlocked devices with others.',
      'Publicly displaying personal identifying information (phone numbers, addresses) on public social media.',
      'Oversharing location check-ins and travel schedules in real time.',
    ],
    examples: [
      'A photo-editing app requesting continuous background location and contact list access without reason.',
      'Leaving account sessions logged in on shared public computers.',
    ],
    saferNextSteps: [
      'Conduct regular audits of installed applications and revoke unnecessary location, microphone, and storage permissions.',
      'Enable Two-Factor Authentication (2FA) using an authenticator app on all critical email and social accounts.',
      'Set social media profiles to private mode and review your friend/follower list periodically.',
      'Use strong, unique passphrases for different online services.',
    ],
    evidenceAndRecordsSafety: [
      'Keep backup codes for two-factor authentication stored safely offline.',
      'Regularly check "Active Sessions" or "Logged in Devices" under account security settings.',
    ],
    whereToLookForHelp: [
      'Official cybersecurity advisories from CERT-In (Computer Emergency Response Team - India).',
      'Platform security and account recovery portals.',
    ],
    relatedLawIds: ['law-it-act-2000'],
    relatedResourceIds: ['res-cyber-portal'],
    relatedGuideSlugs: ['online-abuse-steps'],
    sourceIds: ['src-meity', 'src-mha-ncrp'],
    tags: ['Privacy', 'Cyber Hygiene', 'App Permissions', '2FA', 'Consent'],
    disclaimerText:
      'General cyber hygiene awareness. Review device manufacturer guidelines for specific operating system settings.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-financial-scams-upi-safety',
    slug: 'financial-scams-upi-safety',
    title: 'Financial Scams, Phishing, OTP & UPI Safety',
    category: 'cyber',
    summary: 'Awareness on recognizing digital payment frauds, fake job offers, unauthorized OTP requests, and safe banking practices.',
    plainIntroduction:
      'Financial cyber frauds frequently target citizens through deceptive phone calls, fake part-time work offers, phishing links, and deceptive UPI payment requests. Awareness helps in spotting red flags and acting swiftly to minimize financial harm.',
    whatItMayInclude: [
      'Fraudulent callers posing as bank officials, courier agents, or police asking for OTPs or PINs.',
      'Deceptive QR codes sent with the claim "scan this QR code to receive money" (scanning a QR code or entering a PIN always deducts funds).',
      'Fake work-from-home or task-based investment schemes promising guaranteed daily returns.',
      'Phishing SMS or WhatsApp links asking to update KYC or utility bill details.',
    ],
    examples: [
      'Receiving a message claiming an electric connection will be disconnected unless a link is clicked immediately.',
      'A buyer on an online marketplace asking you to scan a QR code and enter your UPI PIN to receive payment.',
    ],
    saferNextSteps: [
      'Remember: You NEVER need to enter a UPI PIN or OTP to receive money.',
      'Never share bank OTPs, debit card CVV, or passwords with anyone, including individuals claiming to be bank executives.',
      'If you suspect an unauthorized transaction has occurred, contact your bank immediately to freeze the account/cards.',
      'Report immediately to the National Cyber Crime Helpline at 1930.',
    ],
    evidenceAndRecordsSafety: [
      'Preserve transaction IDs, SMS alerts, UPI reference numbers, and fraudster phone numbers.',
      'Do not delete transaction logs or bank statements.',
    ],
    whereToLookForHelp: [
      'National Cyber Financial Fraud Reporting Helpline: 1930.',
      'Official bank 24/7 card block numbers.',
      'National Cyber Crime Reporting Portal: cybercrime.gov.in.',
    ],
    relatedLawIds: ['law-it-act-2000'],
    relatedResourceIds: ['res-cyber-portal', 'res-er-112'],
    relatedGuideSlugs: ['online-abuse-steps'],
    sourceIds: ['src-mha-ncrp', 'src-meity'],
    tags: ['UPI Safety', 'OTP Security', 'Financial Scams', 'Phishing', 'Fraud Prevention'],
    disclaimerText:
      'General financial safety educational guidance. For unauthorized transactions, contact your official bank support immediately.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
  {
    id: 'topic-workplace-sexual-harassment',
    slug: 'workplace-sexual-harassment',
    title: 'Workplace Sexual Harassment & POSH Framework',
    category: 'workplace',
    summary: 'Comprehensive awareness on the POSH Act 2013, Internal Committees, inquiry rights, and protections against retaliation.',
    plainIntroduction:
      'The Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 (POSH Act) provides an institutional framework to prevent and redress sexual harassment across organized, unorganized, government, and private workplaces in India.',
    whatItMayInclude: [
      'Unwelcome physical contact, advances, or inappropriate proximity at work.',
      'Demand or request for sexual favors (quid pro quo harassment).',
      'Making sexually colored remarks, inappropriate jokes, or commentary on physical appearance.',
      'Showing pornography or sending unsolicited explicit messages, emails, or images.',
      'Creating a hostile, intimidating, or offensive work environment.',
    ],
    examples: [
      'A supervisor implying performance reviews or promotions depend on after-hours socializing.',
      'Repeated inappropriate commentary on clothing or personal life in office communications.',
      'Retaliatory actions (such as unfair project reassignments) following refusal of romantic advances.',
    ],
    saferNextSteps: [
      'Document incidents with dates, times, locations, emails, messages, and any witnesses if safe.',
      'Check your workplace policy for the composition and official contact email of the Internal Committee (IC).',
      'Submit a formal written complaint to the IC within 3 months of the incident (or to the District Local Committee if the organization has fewer than 10 employees or the complaint is against the employer).',
      'You may request interim protections (such as transfer or leave) during the inquiry period.',
    ],
    evidenceAndRecordsSafety: [
      'Store relevant emails, screenshots, and communications on personal secure devices outside company servers if safe.',
      'Maintain an objective factual timeline without altering original records.',
      'Never attempt unauthorized access or hazardous confrontations.',
    ],
    whereToLookForHelp: [
      'Workplace Internal Committee (IC) / Presiding Officer.',
      'District Local Committee (LC) constituted by the District Magistrate.',
      'Ministry of Women and Child Development (MWCD) / SHe-Box portal guidance.',
      'District Legal Services Authority (DLSA) for free legal guidance.',
    ],
    relatedLawIds: ['law-posh-act-2013'],
    relatedResourceIds: ['res-ncw-helpline', 'res-nalsa-legal-aid', 'res-one-stop-centres'],
    relatedGuideSlugs: ['workplace-harassment-steps'],
    sourceIds: ['src-mowcd', 'src-ncw', 'src-nalsa'],
    tags: ['POSH Act', 'Internal Committee', 'Workplace Safety', 'Local Committee', 'Anti-Harassment'],
    disclaimerText:
      'General workplace safety awareness only. Specific inquiry rules, timelines, and organizational policies are governed by the POSH Act and company service regulations.',
    lastReviewedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'needs-verification',
    publicationState: 'published',
  },
];
