import { SourceCitation } from '@/types/content';

export const officialSources: SourceCitation[] = [
  {
    id: 'src-mha-erss',
    title: 'Emergency Response Support System (ERSS - 112)',
    organization: 'Ministry of Home Affairs, Government of India',
    category: 'Emergency Dispatch',
    url: 'https://112.gov.in',
    lastVerifiedDate: '2026-03-01',
    verificationStatus: 'verified',
    description: 'Unified national 24/7 emergency response service connecting citizens to police, fire, and medical teams.',
  },
  {
    id: 'src-mowcd',
    title: 'Ministry of Women and Child Development (MWCD)',
    organization: 'Government of India',
    category: 'Government Ministry',
    url: 'https://wcd.nic.in',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    description: 'Nodal ministry responsible for statutory policies, POSH rules, Domestic Violence Act rules, and One Stop Centres.',
  },
  {
    id: 'src-ncw',
    title: 'National Commission for Women (NCW)',
    organization: 'Statutory Body, Government of India',
    category: 'Statutory Commission',
    url: 'http://ncw.nic.in',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    description: 'Apex constitutional and statutory body mandated to investigate complaints and safeguard women’s rights in India.',
  },
  {
    id: 'src-nalsa',
    title: 'National Legal Services Authority (NALSA)',
    organization: 'Statutory Body under Legal Services Authorities Act, 1987',
    category: 'Legal Aid & Justice',
    url: 'https://nalsa.gov.in',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    description: 'Statutory institution offering free, competent legal services to eligible persons including women under Section 12(c).',
  },
  {
    id: 'src-mha-ncrp',
    title: 'National Cyber Crime Reporting Portal (NCRP)',
    organization: 'Ministry of Home Affairs, Government of India',
    category: 'Cyber Safety & Law Enforcement',
    url: 'https://cybercrime.gov.in',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    description: 'Official national online platform for registering complaints relating to cyber crimes against women and children.',
  },
  {
    id: 'src-law-min',
    title: 'Legislative Department, Ministry of Law and Justice',
    organization: 'Government of India',
    category: 'Statute Repository',
    url: 'https://legislative.gov.in',
    lastVerifiedDate: '2026-01-20',
    verificationStatus: 'placeholder',
    description: 'Official repository of acts, statutes, and gazette notifications passed by the Parliament of India.',
  },
];
