import { SourceCitation } from '@/types/content';

export const officialSources: SourceCitation[] = [
  {
    id: 'src-mha-erss',
    title: 'Emergency Response Support System (ERSS - 112)',
    organization: 'Ministry of Home Affairs, Government of India',
    publisher: 'Ministry of Home Affairs, Government of India',
    category: 'Emergency Dispatch',
    url: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    officialSourceUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    lastVerifiedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    accessedAt: '2026-03-01',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '112 is India’s nationwide unified emergency number.',
    limitations: 'National emergency number only; operational dispatch is handled by respective State/UT Emergency Response Centres.',
    description: 'Unified national 24/7 emergency response service connecting citizens to police, fire, and medical teams.',
  },
  {
    id: 'src-mowcd-whl',
    title: 'Mission Shakti - Women Helpline 181',
    organization: 'Ministry of Women and Child Development, Government of India',
    publisher: 'Ministry of Women and Child Development, Government of India',
    category: 'National Programme & Helpline',
    url: 'https://missionshakti.wcd.gov.in/',
    officialSourceUrl: 'https://missionshakti.wcd.gov.in/',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    accessedAt: '2026-10-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'Mission Shakti lists Women Helpline 181 and describes the One Stop Centre scheme as providing integrated support and assistance.',
    limitations: 'National programme information verified; local routing, state telecom operational availability, and district response times require separate verification.',
    description: 'Integrated national scheme under Sambal sub-scheme providing 24-hour toll-free emergency and non-emergency helpline support.',
  },
  {
    id: 'src-mowcd-osc',
    title: 'Sakhi One Stop Centre (OSC) Scheme',
    organization: 'Ministry of Women and Child Development, Government of India',
    publisher: 'Ministry of Women and Child Development, Government of India',
    category: 'Institutional Support Services',
    url: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    officialSourceUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    accessedAt: '2026-10-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'Mission Shakti describes the One Stop Centre scheme as providing integrated support and assistance.',
    limitations: 'National programme information verified. Do not mark any district address, local phone number, office hours, or specific centre contact as verified without separate district/state sources.',
    description: 'Centrally sponsored initiative offering integrated medical, legal, psychological, and temporary shelter assistance under one roof.',
  },
  {
    id: 'src-ncw',
    title: 'National Commission for Women (NCW) Women Helpline (14490)',
    organization: 'National Commission for Women, Government of India',
    publisher: 'National Commission for Women, Government of India',
    category: 'Statutory Commission',
    url: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    officialSourceUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    accessedAt: '2026-10-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'NCW Women Helpline 14490 is an official NCW helpline for women in distress and support/referral information.',
    limitations: 'National NCW helpline description and 14490 only. Do not display unsupported operating details.',
    description: 'Statutory national commission helpline established to provide round-the-clock support, counselling, and institutional grievance intervention.',
  },
  {
    id: 'src-nalsa',
    title: 'National Legal Services Authority (NALSA) Toll-Free Legal Aid (15100)',
    organization: 'National Legal Services Authority (NALSA)',
    publisher: 'National Legal Services Authority (NALSA)',
    category: 'Legal Aid & Justice',
    url: 'https://nalsa.gov.in/',
    officialSourceUrl: 'https://nalsa.gov.in/',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    accessedAt: '2026-10-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'NALSA identifies 15100 as its toll-free legal-aid helpline.',
    limitations: 'National NALSA legal-aid helpline and general legal-aid description. Court advocate assignment requires coordination with jurisdictional DLSA clinics.',
    description: 'Statutory institution offering free, competent legal services to eligible persons including women under Section 12(c) of the Legal Services Authorities Act, 1987.',
  },
  {
    id: 'src-mha-ncrp',
    title: 'Citizen Financial Cyber Fraud Reporting System & Helpline (1930)',
    organization: 'Ministry of Home Affairs, Government of India',
    publisher: 'Ministry of Home Affairs, Government of India',
    category: 'Cyber Safety & Law Enforcement',
    url: 'https://cybercrime.gov.in',
    officialSourceUrl: 'https://cybercrime.gov.in',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    accessedAt: '2026-10-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '1930 is the national cybercrime helpline dedicated to citizen financial cyber fraud reporting.',
    limitations: 'Helpline specifically dedicated to online financial fraud incidents. Not a universal emergency dispatch number; not the investigative route for every non-financial cyber offense.',
    description: 'Official national online platform and 1930 helpline for registering complaints regarding cyber offences, online financial scams, and objectionable media.',
  },
  {
    id: 'src-law-min',
    title: 'Legislative Department, Ministry of Law and Justice',
    organization: 'Ministry of Law and Justice, Government of India',
    publisher: 'Government of India',
    category: 'Statute Repository',
    url: 'https://legislative.gov.in',
    officialSourceUrl: 'https://legislative.gov.in',
    lastVerifiedDate: '2026-01-20',
    nextReviewDueDate: '2026-07-20',
    accessedAt: '2026-01-20',
    verificationStatus: 'needs-verification',
    verificationScope: 'pending',
    verifiedClaim: 'Official legislative text repository for Acts of Parliament.',
    limitations: 'Verify statute gazette versions before public reliance.',
    description: 'Official repository of acts, statutes, and gazette notifications passed by the Parliament of India.',
  },
];
