import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'राष्ट्रीय आपत्कालीन प्रतिसाद (पोलीस / अग्निशामक / रुग्णवाहिका)',
    number: '112',
    description: 'तातडीच्या आपत्कालीन साहाय्यासाठी 24/7 एकात्मिक देशव्यापी आपत्कालीन सेवा.',
    available: '24/7 टोल-फ्री',
    isClickableEmergency: true,
  },
  {
    label: 'महिला हेल्पलाइन (मिशन शक्ती)',
    number: '181',
    description: 'संकटग्रस्त महिलांसाठी राष्ट्रीय कार्यक्रम हेल्पलाइन. स्थानिक केंद्र तपशीलांची स्वतंत्र पडताळणी आवश्यक आहे.',
    available: '24/7 राष्ट्रीय कार्यक्रम संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय महिला आयोग (NCW) हेल्पलाइन',
    number: '14490',
    description: 'संकटग्रस्त महिलांसाठी आणि मदत संदर्भासाठी राष्ट्रीय महिला आयोगाची अधिकृत हेल्पलाइन.',
    available: 'राष्ट्रीय एनसीडब्ल्यू संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'नालसा (NALSA) कायदेशीर मदत हेल्पलाइन',
    number: '15100',
    description: 'वैधानिक अधिकार आणि कायदेशीर साहाय्यासाठी देशव्यापी टोल-फ्री हेल्पलाइन.',
    available: 'राष्ट्रीय कायदेशीर मदत संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय सायबर गुन्हे हेल्पलाइन',
    number: '1930 (सार्वजनिक वापरापूर्वी अधिकृत स्रोताकडून खात्री करा)',
    description: 'सायबर आर्थिक फसवणूक आणि डिजिटल गुन्ह्यांसाठी तक्रार हेल्पलाइन संदर्भ. नोंदणी पडताळणी प्रलंबित.',
    available: 'पडताळणी प्रलंबित संदर्भ',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'आपत्कालीन प्रतिसाद साहाय्य प्रणाली (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'नागरिकांना स्थानिक पोलीस, वैद्यकीय आणि अग्निशामक पथकांशी थेट जोडणारे देशव्यापी आपत्कालीन व्यासपीठ.',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    officialSourceUrl: 'https://www.mha.gov.in/en/commoncontent/emergency-response-support-system-erss',
    sourceTitle: 'Emergency Response Support System (ERSS)',
    publisher: 'गृह मंत्रालय, भारत सरकार',
    accessedAt: '2026-03-01',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    nextReviewDueDate: '2026-09-01',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: '112 हा भारताचा देशव्यापी एकात्मिक आपत्कालीन क्रमांक आहे.',
    limitations: 'केवळ राष्ट्रीय आपत्कालीन क्रमांक; प्रत्यक्ष मदत संबंधित राज्य/केंद्रशासित प्रदेशांच्या आपत्कालीन प्रतिसाद केंद्रांमार्फत केली जाते.',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'अधिकृत 24/7 देशव्यापी आपत्कालीन क्रमांक. थेट आपत्कालीन कॉलिंगसाठी वापरता येणारा.',
    isEmergency112: true,
  },
  {
    id: 'res-whl-181',
    name: 'महिला हेल्पलाइन (181 - मिशन शक्ती)',
    category: 'National Helpline',
    description:
      'मिशन शक्ती अंतर्गत संकटग्रस्त महिलांना आपत्कालीन आणि बिगर-आपत्कालीन संदर्भ, समुपदेशन आणि वन स्टॉप सेंटर्सशी समन्वय देणारी राष्ट्रीय 24/7 टोल-फ्री हेल्पलाइन.',
    contactType: 'phone',
    contactValue: '181',
    officialUrl: 'https://missionshakti.wcd.gov.in/',
    officialSourceUrl: 'https://missionshakti.wcd.gov.in/',
    sourceTitle: 'Mission Shakti - Women Helpline 181 Guidelines',
    publisher: 'महिला आणि बालविकास मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'महिला आणि बालविकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd-whl',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'मिशन शक्ती महिला हेल्पलाइन 181 ची नोंद करते आणि एकात्मिक साहाय्य देण्यासाठी वन स्टॉप सेंटर योजनेचे वर्णन करते.',
    limitations: 'राष्ट्रीय कार्यक्रमाची माहिती पडताळली आहे; स्थानिक टेलिकॉम राउटिंग आणि राज्यस्तरीय उपलब्धतेची स्वतंत्र पडताळणी आवश्यक आहे.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'राष्ट्रीय कार्यक्रम माहिती पडताळली; स्थानिक तपशीलांची स्वतंत्र पडताळणी आवश्यक आहे. क्लिक न करता येणारा संदर्भ.',
    isEmergency112: false,
  },
  {
    id: 'res-one-stop-centres',
    name: 'सखी वन स्टॉप सेंटर्स (Sakhi OSC Scheme)',
    category: 'Counseling & Support',
    description:
      'हिंसाचारग्रस्त महिलांना वैद्यकीय मदत, पोलीस साहाय्य, कायदेशीर मदत आणि तात्पुरता निवारा देणारी एकात्मिक जिल्हास्तरीय साहाय्य केंद्रे.',
    contactType: 'in-person',
    contactValue: 'जिल्हा रुग्णालय / नियुक्त ओएससी संकुल (स्थानिक पातळीवर पडताळणी करा)',
    officialUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    officialSourceUrl: 'https://wcd.gov.in/offerings/one-stop-centre-scheme',
    sourceTitle: 'One Stop Centre Scheme Guidelines & Mission Shakti',
    publisher: 'महिला आणि बालविकास मंत्रालय, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'महिला आणि बालविकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd-osc',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-programme',
    verifiedClaim: 'मिशन शक्ती वन स्टॉप सेंटर योजनेचे एकात्मिक साहाय्य आणि मदत देणारी व्यवस्था म्हणून वर्णन करते.',
    limitations: 'राष्ट्रीय कार्यक्रमाची माहिती पडताळली आहे. स्वतंत्र जिल्हा/राज्य स्रोतांशिवाय स्थानिक पत्ता, संपर्क क्रमांक किंवा कार्यालयीन वेळेस पडताळलेले मानू नका.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'राष्ट्रीय कार्यक्रम माहिती पडताळली; स्थानिक केंद्र तपशीलांची स्वतंत्र पडताळणी आवश्यक आहे. प्रत्यक्ष भेट संदर्भ.',
    isEmergency112: false,
  },
  {
    id: 'res-ncw-helpline',
    name: 'राष्ट्रीय महिला आयोग (NCW) महिला हेल्पलाइन',
    category: 'National Helpline',
    description:
      'संकटग्रस्त महिलांसाठी राष्ट्रीय महिला आयोगाची अधिकृत हेल्पलाइन, जी साहाय्य, तक्रार निवारण आणि संस्थागत मार्गदर्शनाची सुविधा देते.',
    contactType: 'phone',
    contactValue: '14490',
    officialUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    officialSourceUrl: 'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
    sourceTitle: 'NCW Cells - NCW Women Helpline (14490)',
    publisher: 'राष्ट्रीय महिला आयोग, भारत सरकार',
    accessedAt: '2026-10-08',
    sourceOwner: 'राष्ट्रीय महिला आयोग (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'एनसीडब्ल्यू महिला हेल्पलाइन 14490 ही संकटातील महिलांसाठी आणि साहाय्य/संदर्भ माहितीसाठी अधिकृत एनसीडब्ल्यू हेल्पलाइन आहे.',
    limitations: 'केवळ राष्ट्रीय एनसीडब्ल्यू हेल्पलाइन वर्णन आणि 14490; असमर्थित तपशील प्रदर्शित करू नका.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'पडताळलेला राष्ट्रीय संपर्क. टेलिफोन क्रमांक क्लिक न करता येणारा संदर्भ म्हणून दर्शविला आहे. थेट 14490 डायल करा.',
    isEmergency112: false,
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'राष्ट्रीय विधी सेवा प्राधिकरण (NALSA) कायदेशीर मदत हेल्पलाइन',
    category: 'Legal Aid',
    description:
      'विधी सेवा प्राधिकरण कायद्याच्या कलम 12(c) अन्वये महिलांसह पात्र व्यक्तींना मोफत कायदेशीर सल्ला, वकील नियुक्ती आणि साहाय्य देणारी वैधानिक संस्था.',
    contactType: 'phone',
    contactValue: '15100',
    officialUrl: 'https://nalsa.gov.in/',
    officialSourceUrl: 'https://nalsa.gov.in/',
    sourceTitle: 'National Legal Services Authority Legal Aid Portal & FAQs',
    publisher: 'राष्ट्रीय विधी सेवा प्राधिकरण (NALSA)',
    accessedAt: '2026-10-08',
    sourceOwner: 'राष्ट्रीय विधी सेवा प्राधिकरण (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-10-08',
    nextReviewDueDate: '2027-04-08',
    verificationStatus: 'verified',
    verificationScope: 'national-contact',
    verifiedClaim: 'नालसा (NALSA) 15100 ला आपली टोल-फ्री कायदेशीर मदत हेल्पलाइन म्हणून निर्देशित करते.',
    limitations: 'राष्ट्रीय नालसा कायदेशीर मदत हेल्पलाइन आणि सामान्य कायदेशीर मदत वर्णन. स्थानिक वकील नियुक्तीसाठी जिल्हा डीएलएसएशी समन्वय आवश्यक आहे.',
    publicationStatus: 'published',
    reviewDate: '2027-04-08',
    safeDisplayNote: 'पडताळलेला राष्ट्रीय संपर्क. टेलिफोन क्रमांक क्लिक न करता येणारा संदर्भ म्हणून दर्शविला आहे. थेट 15100 डायल करा.',
    isEmergency112: false,
  },
  {
    id: 'res-cyber-portal',
    name: 'राष्ट्रीय सायबर गुन्हे नोंदणी पोर्टल (cybercrime.gov.in)',
    category: 'Cyber Crime',
    description:
      'महिलांवरील सायबर गुन्हे, ऑनलाइन छळ आणि आक्षेपार्ह मीडियाच्या तक्रारी नोंदवण्यासाठी गृह मंत्रालयाचे अधिकृत पोर्टल.',
    contactType: 'portal',
    contactValue: 'हेल्पलाइन 1930 / cybercrime.gov.in',
    officialUrl: 'https://cybercrime.gov.in',
    officialSourceUrl: 'https://cybercrime.gov.in',
    sourceTitle: 'National Cyber Crime Reporting Portal (NCRP)',
    publisher: 'गृह मंत्रालय, भारत सरकार',
    accessedAt: '2026-02-15',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-02-15',
    nextReviewDueDate: '2026-08-15',
    verificationStatus: 'needs-verification',
    verificationScope: 'pending',
    verifiedClaim: 'एनसीआरपी पोर्टल आणि 1930 हेल्पलाइन नोंदीसाठी अधिकृत स्रोत नोंदणी पडताळणी प्रलंबित आहे.',
    limitations: 'लाँच करण्यापूर्वी ही संपर्क माहिती अधिकृत स्रोताकडून पडताळून पहा.',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'सार्वजनिक वापरापूर्वी अधिकृत स्रोताकडून खात्री करा. शैक्षणिक संदर्भासाठी अधिकृत पोर्टल लिंक.',
    isEmergency112: false,
  },
];
