import { HelpResource, EmergencyContact } from '@/types/resources';

export const emergencyContacts: EmergencyContact[] = [
  {
    label: 'राष्ट्रीय आपत्कालीन प्रतिसाद (पोलीस / अग्निशामक / रुग्णवाहिका)',
    number: '112',
    description: 'तातडीच्या आपत्कालीन साहाय्यासाठी 24/7 एकात्मिक देशव्यापी आपत्कालीन सेवा.',
    available: '24/7 टोल-फ्री',
    isClickableEmergency: true,
  },
  {
    label: 'महिला हेल्पलाइन (राष्ट्रीय)',
    number: '1091 (सार्वजनिक वापरापूर्वी अधिकृत स्रोताकडून खात्री करा)',
    description: 'संकटग्रस्त महिलांसाठी हेल्पलाइन संदर्भ. प्रशासकीय पडताळणीच्या अधीन.',
    available: 'टोल-फ्री संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय सायबर गुन्हे हेल्पलाइन',
    number: '1930 (सार्वजनिक वापरापूर्वी अधिकृत स्रोताकडून खात्री करा)',
    description: 'सायबर आर्थिक फसवणूक आणि डिजिटल गुन्ह्यांसाठी सरकारी तक्रार हेल्पलाइन.',
    available: 'राष्ट्रीय संदर्भ',
    isClickableEmergency: false,
  },
  {
    label: 'राष्ट्रीय महिला आयोग (NCW)',
    number: '7827170170 (सार्वजनिक वापरापूर्वी अधिकृत स्रोताकडून खात्री करा)',
    description: 'समुपदेशन आणि प्रक्रियात्मक मार्गदर्शनासाठी राष्ट्रीय महिला आयोग हेल्पलाइन संदर्भ.',
    available: 'मदत केंद्र संदर्भ',
    isClickableEmergency: false,
  },
];

export const helpResourcesData: HelpResource[] = [
  {
    id: 'res-er-112',
    name: 'आपत्कालीन प्रतिसाद साहाय्य प्रणाली (ERSS - 112)',
    category: 'Police & Emergency',
    description:
      'नागरिकांना स्थानिक पोलीस, वैद्यकीय आणि अग्निशामक पथकांशी थेट जोडणारे देशव्यापी आपत्कालीन व्यासपीठ.',
    contactType: 'phone',
    contactValue: '112',
    officialUrl: 'https://112.gov.in',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-erss',
    lastVerifiedDate: '2026-03-01',
    verificationStatus: 'verified',
    publicationStatus: 'published',
    reviewDate: '2026-09-01',
    safeDisplayNote: 'अधिकृत 24/7 देशव्यापी आपत्कालीन क्रमांक. थेट आपत्कालीन कॉलिंगसाठी वापरता येणारा.',
    isEmergency112: true,
  },
  {
    id: 'res-one-stop-centres',
    name: 'सखी वन स्टॉप सेंटर्स (Sakhi OSC)',
    category: 'Counseling & Support',
    description:
      'हिंसाचारग्रस्त महिलांना वैद्यकीय मदत, पोलीस साहाय्य, कायदेशीर मदत आणि तात्पुरता निवारा देणारी एकात्मिक साहाय्य केंद्रे.',
    contactType: 'in-person',
    contactValue: 'जिल्हा रुग्णालय / नियुक्त ओएससी संकुल',
    officialUrl: 'https://wcd.nic.in',
    sourceOwner: 'महिला आणि बालविकास मंत्रालय (MWCD)',
    sourceId: 'src-mowcd',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'भेट देण्यापूर्वी अधिकृत जिल्हा प्रशासनाकडून स्थानिक केंद्राचा पत्ता आणि संपर्क तपासा.',
  },
  {
    id: 'res-ncw-helpline',
    name: 'राष्ट्रीय महिला आयोग (NCW) 24/7 हेल्पलाइन',
    category: 'National Helpline',
    description:
      'हिंसाचार किंवा हक्कांचे उल्लंघन सहन करणाऱ्या महिलांसाठी तक्रार निवारण आणि समुपदेशन सुलभ करणारी हेल्पलाइन.',
    contactType: 'phone',
    contactValue: '7827170170 (प्लेसहोल्डर - वापरापूर्वी पडताळणी करा)',
    officialUrl: 'http://ncw.nic.in',
    sourceOwner: 'राष्ट्रीय महिला आयोग (NCW)',
    sourceId: 'src-ncw',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'क्लिक न करता येणारा संदर्भ. वापरापूर्वी अधिकृत एनसीडब्ल्यू पोर्टलवरून खात्री करा.',
  },
  {
    id: 'res-nalsa-legal-aid',
    name: 'राष्ट्रीय विधी सेवा प्राधिकरण (NALSA) / डीएलएसए क्लिनिक',
    category: 'Legal Aid',
    description:
      'कलम 12(c) अन्वये महिलांसह पात्र व्यक्तींना मोफत कायदेशीर सल्ला, वकील नियुक्ती आणि साहाय्य देणारी वैधानिक संस्था.',
    contactType: 'mixed',
    contactValue: 'हेल्पलाइन 15100 / जिल्हा न्यायालय संकुल डीएलएसए कार्यालये',
    officialUrl: 'https://nalsa.gov.in',
    sourceOwner: 'राष्ट्रीय विधी सेवा प्राधिकरण (NALSA)',
    sourceId: 'src-nalsa',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'अधिकृत कायदेशीर सल्ल्यासाठी जिल्हा न्यायालय संकुलातील जवळच्या जिल्हा विधी सेवा प्राधिकरण (DLSA) कार्यालयाशी संपर्क साधा.',
  },
  {
    id: 'res-cyber-portal',
    name: 'राष्ट्रीय सायबर गुन्हे नोंदणी पोर्टल (cybercrime.gov.in)',
    category: 'Cyber Crime',
    description:
      'महिलांवरील सायबर गुन्हे, ऑनलाइन छळ आणि आक्षेपार्ह मीडियाच्या तक्रारी नोंदवण्यासाठी गृह मंत्रालयाचे अधिकृत पोर्टल.',
    contactType: 'portal',
    contactValue: 'हेल्पलाइन 1930 / cybercrime.gov.in',
    officialUrl: 'https://cybercrime.gov.in',
    sourceOwner: 'गृह मंत्रालय, भारत सरकार',
    sourceId: 'src-mha-ncrp',
    lastVerifiedDate: '2026-02-15',
    verificationStatus: 'placeholder',
    publicationStatus: 'published',
    reviewDate: '2026-08-15',
    safeDisplayNote: 'शैक्षणिक संदर्भासाठी अधिकृत पोर्टल लिंक. तक्रार दाखल करण्यापूर्वी ब्राउझर सुरक्षा प्रमाणपत्राची पडताळणी करा.',
  },
];
